---
version: "3.7"
services:
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    restart: unless-stopped
    container_name: heimdall
    environment:
#      - PUID=1000
#      - PGID=1000
      - TZ=Europe/Kiev
    volumes:
      - ./config:/config
    networks:
        traefik-public:
    labels:
      - "traefik.enable=true"
#      - "traefik.http.routers.heim.rule=Host(`nas.voronenko.net`)"
#      - "traefik.http.routers.heim.entrypoints=web"
      - "traefik.http.services.heim.loadbalancer.server.port=80"

#      - "traefik.http.middlewares.traefik-auth.basicauth.users=USER:PASSWORD"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"

      - "traefik.http.routers.heim-secure.entrypoints=websecure"
      - "traefik.http.routers.heim-secure.rule=Host(`nas.voronenko.net`)"
#      - "traefik.http.routers.heim-secure.middlewares=traefik-auth"
      - "traefik.http.routers.heim-secure.tls=true"

    restart: unless-stopped
networks:
  traefik-public:
    external: true

